apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-config

data:
  ROOT_PATH: "/app1"
  CLIENT_ID: "2e9b7a1dd3f3b0db7f37871a7124ca1b"
  CLIENT_SECRET: "3167u6QZTxs2iGA4ET2CogzPi0qR3uI7"

  REDIRECT_URI: "http://aiedu.tplinkdns.com:6204/app1/oauth/callback/kakao"
  DNS: "aiedu.tplinkdns.com"
  SECURE: "False"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_ACCESS_DB: "0"
  REDIS_REFRESH_DB: "1"