apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-label
  name: app-dp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-label
  strategy: {}
  template:
    metadata:
      labels:
        app: app-label
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        resources: {}
status: {}
